from typing import Any, Dict, Type

class Resource:
    def __init__(self) -> None: ...

class Api:
    def __init__(self, app: Any = None, **kwargs: Any) -> None: ...
    def add_resource(self, resource: Type[Resource], *urls: str, **kwargs: Any) -> None: ...

class reqparse:
    class RequestParser:
        def __init__(self) -> None: ...
        def add_argument(self, name: str, **kwargs: Any) -> None: ...
        def parse_args(self, req: Any = None, strict: bool = False) -> Dict[str, Any]: ...

